[[xrootdgo]]
arch = "aarch64"
git-tree-sha1 = "686225b306d23774afb38342aa461a4e94a6897e"
os = "macos"

    [[xrootdgo.download]]
    sha256 = "b12ea8f9fd17b2af91badb373fe45222190b873d13c746f0c034d3e9afe30001"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.34.1+0/xrootdgo.v0.34.1.aarch64-apple-darwin.tar.gz"
[[xrootdgo]]
arch = "aarch64"
git-tree-sha1 = "33dceb19d381b3b336aaa3ec9dc07e6b274897f8"
libc = "glibc"
os = "linux"

    [[xrootdgo.download]]
    sha256 = "4fdc67ed16f34b551327d4d242f988e7ce5ad1306a994f199e7938fc808510f0"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.34.1+0/xrootdgo.v0.34.1.aarch64-linux-gnu.tar.gz"
[[xrootdgo]]
arch = "aarch64"
git-tree-sha1 = "aaad991cf068612bc998b238770ea30e3d41a7d3"
libc = "musl"
os = "linux"

    [[xrootdgo.download]]
    sha256 = "e83dc523343a0761f0ce90a8401500e7398e7deb0e5ebcefd3d119a2b27a5444"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.34.1+0/xrootdgo.v0.34.1.aarch64-linux-musl.tar.gz"
[[xrootdgo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f7124e906cc4b4bcc8a2a5bcf198ef0aefa00c22"
libc = "glibc"
os = "linux"

    [[xrootdgo.download]]
    sha256 = "2c796bb9dcd42580fdf44c234b3252d772e59610a29449d1f3024019177726d0"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.34.1+0/xrootdgo.v0.34.1.armv6l-linux-gnueabihf.tar.gz"
[[xrootdgo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0728e06057f6240b2075bc2dfbc0df2b6d649e80"
libc = "musl"
os = "linux"

    [[xrootdgo.download]]
    sha256 = "dddc709d9b433de911e58d2443cf60e6323e1ca5e397b73cae05768bb9591c76"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.34.1+0/xrootdgo.v0.34.1.armv6l-linux-musleabihf.tar.gz"
[[xrootdgo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b468b515a2f85234d7a6c3f12b9063a7f144fb48"
libc = "glibc"
os = "linux"

    [[xrootdgo.download]]
    sha256 = "825f9171f797bc088a5e5b624527344888eaea23c3f287b8f9128d300d39f639"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.34.1+0/xrootdgo.v0.34.1.armv7l-linux-gnueabihf.tar.gz"
[[xrootdgo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6ed5c9a847c20a9e89c3ba60f0e5cf436a2206b1"
libc = "musl"
os = "linux"

    [[xrootdgo.download]]
    sha256 = "460278f03da10ab763c80aeaeab6bbf12a53aea4f32cc00b25c3bc6b8c233bd3"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.34.1+0/xrootdgo.v0.34.1.armv7l-linux-musleabihf.tar.gz"
[[xrootdgo]]
arch = "i686"
git-tree-sha1 = "82dc78229e5da775730890357b5b7b287786932f"
libc = "glibc"
os = "linux"

    [[xrootdgo.download]]
    sha256 = "dc081c9bcb20f84c65050276477c9b711f295ad9cb8e9e21e7a081b88bdefa8a"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.34.1+0/xrootdgo.v0.34.1.i686-linux-gnu.tar.gz"
[[xrootdgo]]
arch = "i686"
git-tree-sha1 = "e05c3dfa02ff2d997ad39e2d32d6762a8cac1886"
libc = "musl"
os = "linux"

    [[xrootdgo.download]]
    sha256 = "5567b1f1e58b3ae7a973adc88d420a4e8317bcf928c8e8572bf441a3f8249a38"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.34.1+0/xrootdgo.v0.34.1.i686-linux-musl.tar.gz"
[[xrootdgo]]
arch = "i686"
git-tree-sha1 = "bc85bcb9b4914750fb7ddfe0edd33483b13df213"
os = "windows"

    [[xrootdgo.download]]
    sha256 = "77404a0cb0549303548572b1d382497f2265dd41bf4cdaf1929f1e59925b8608"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.34.1+0/xrootdgo.v0.34.1.i686-w64-mingw32.tar.gz"
[[xrootdgo]]
arch = "powerpc64le"
git-tree-sha1 = "4e2f64d62f1e1cce2ed08714e02b8b216df21676"
libc = "glibc"
os = "linux"

    [[xrootdgo.download]]
    sha256 = "cc39d98625f179b4c852d69e0e8cb2e556ab6619b4ec1122bf5685edf67eb842"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.34.1+0/xrootdgo.v0.34.1.powerpc64le-linux-gnu.tar.gz"
[[xrootdgo]]
arch = "x86_64"
git-tree-sha1 = "00641afae5bdf2519bc374e20e4c573a9962ed16"
os = "macos"

    [[xrootdgo.download]]
    sha256 = "5743eb95b68b0613bf432da9098ea84d4d5a2e84d31cd86cb63ed5744100b058"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.34.1+0/xrootdgo.v0.34.1.x86_64-apple-darwin.tar.gz"
[[xrootdgo]]
arch = "x86_64"
git-tree-sha1 = "f348b81c9716ad66cbfc57f6038044401ef84eec"
libc = "glibc"
os = "linux"

    [[xrootdgo.download]]
    sha256 = "19fb92260d4ac5eaf8b411cdf92b3a20edea6d2b46b74534e743349ecb79e1d1"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.34.1+0/xrootdgo.v0.34.1.x86_64-linux-gnu.tar.gz"
[[xrootdgo]]
arch = "x86_64"
git-tree-sha1 = "4b0070be5ce541d4acc2971f7a65cfb069b8efb7"
libc = "musl"
os = "linux"

    [[xrootdgo.download]]
    sha256 = "9d9fa9dd95c7dcf63d78a132144b0e06309dcfaa13c69d7f1147d9a702ac5a95"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.34.1+0/xrootdgo.v0.34.1.x86_64-linux-musl.tar.gz"
[[xrootdgo]]
arch = "x86_64"
git-tree-sha1 = "be90fa60dd0f9f92575679434b40c12de5ea6b7c"
os = "freebsd"

    [[xrootdgo.download]]
    sha256 = "f18d1fbd79e78229e927cb9c0901e36fd6175f9ecacad76ff02391d8b22dfef9"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.34.1+0/xrootdgo.v0.34.1.x86_64-unknown-freebsd.tar.gz"
[[xrootdgo]]
arch = "x86_64"
git-tree-sha1 = "df55ffbb26295ba626b3bdd9dd313a1525054ec4"
os = "windows"

    [[xrootdgo.download]]
    sha256 = "2b86d240cc2d2eafdf33b21b761598ada3a53e6ebd55997100556740bc4d7585"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.34.1+0/xrootdgo.v0.34.1.x86_64-w64-mingw32.tar.gz"
