[[xrootdgo]]
arch = "aarch64"
git-tree-sha1 = "bdbf2fdf7befc6fa0aabf8cc3aabd6cf351375d1"
os = "macos"

    [[xrootdgo.download]]
    sha256 = "7e5b046bfe532237bdd8896648496d9ecadda278499b3ef03453acd87ac415cb"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.32.1+0/xrootdgo.v0.32.1.aarch64-apple-darwin.tar.gz"
[[xrootdgo]]
arch = "aarch64"
git-tree-sha1 = "db02abaa9f674b75171e21f71ce4ae4a289316b5"
libc = "glibc"
os = "linux"

    [[xrootdgo.download]]
    sha256 = "ba84ab93001fd5f8431c25f3e9745398e58e4677862eef863612cca9145cf261"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.32.1+0/xrootdgo.v0.32.1.aarch64-linux-gnu.tar.gz"
[[xrootdgo]]
arch = "aarch64"
git-tree-sha1 = "172a61d4df88c23cf7acb0e3e1126fd894d7d3b4"
libc = "musl"
os = "linux"

    [[xrootdgo.download]]
    sha256 = "ea55f882a5de40b8cf29fc5fd003bb010a530971376d95b97298259ec78b57a9"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.32.1+0/xrootdgo.v0.32.1.aarch64-linux-musl.tar.gz"
[[xrootdgo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8d2871394f3d95f74b29c18072c9a6dd19532337"
libc = "glibc"
os = "linux"

    [[xrootdgo.download]]
    sha256 = "4f6f84c054be291dfd97cd6a0152379896ec03116524d3ce703759185f221299"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.32.1+0/xrootdgo.v0.32.1.armv6l-linux-gnueabihf.tar.gz"
[[xrootdgo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9a88078046b6f63651667960d780b4537fd42856"
libc = "musl"
os = "linux"

    [[xrootdgo.download]]
    sha256 = "adeadd62af444c7c952d95a2e1fbcb897e215919ef3cf3e84cba4eb1b25c98b9"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.32.1+0/xrootdgo.v0.32.1.armv6l-linux-musleabihf.tar.gz"
[[xrootdgo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4a8f7cdf7f3ac8e6e168dbaa8ba82ea3c876d58e"
libc = "glibc"
os = "linux"

    [[xrootdgo.download]]
    sha256 = "f37be9bd96145927bdefadb7f478f9a3b72ede31ebb0ed1499b58e5ad6426085"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.32.1+0/xrootdgo.v0.32.1.armv7l-linux-gnueabihf.tar.gz"
[[xrootdgo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "790a6acc2412ff43bdd874e09bb57741a4f454d1"
libc = "musl"
os = "linux"

    [[xrootdgo.download]]
    sha256 = "4efb96513ee22b2845090918aaf672abb2d1abf64d724aa79663f6d2fa04e489"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.32.1+0/xrootdgo.v0.32.1.armv7l-linux-musleabihf.tar.gz"
[[xrootdgo]]
arch = "i686"
git-tree-sha1 = "a583e96462cae48a32c7b9c20ab67bcb592e4e15"
libc = "glibc"
os = "linux"

    [[xrootdgo.download]]
    sha256 = "82691f9d842744085f879dad5e87711b57f11d98a7724c8f0f25a94d8f26aec9"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.32.1+0/xrootdgo.v0.32.1.i686-linux-gnu.tar.gz"
[[xrootdgo]]
arch = "i686"
git-tree-sha1 = "a652c3de69487f9f8c09bb27d024875d73d93ef1"
libc = "musl"
os = "linux"

    [[xrootdgo.download]]
    sha256 = "c1396dcbc71bb37e41faa14c6d9dd5aff2fdd2e14f9fc346fc1a52e832a0e07a"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.32.1+0/xrootdgo.v0.32.1.i686-linux-musl.tar.gz"
[[xrootdgo]]
arch = "i686"
git-tree-sha1 = "76456acbab79ab164485ecb622c0c123bdef1e13"
os = "windows"

    [[xrootdgo.download]]
    sha256 = "d2851f18cd991e92f54c1e5ba034ea7dbae344c9d00be3fcb1f100f3427f54ee"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.32.1+0/xrootdgo.v0.32.1.i686-w64-mingw32.tar.gz"
[[xrootdgo]]
arch = "powerpc64le"
git-tree-sha1 = "5e5e7eb58faf0d997f0e9192aa779314ee60cd8f"
libc = "glibc"
os = "linux"

    [[xrootdgo.download]]
    sha256 = "b8a0ccd9db0f21fb5db03e8d76808b68fa9df2173e89b8195eff4a9c9700c331"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.32.1+0/xrootdgo.v0.32.1.powerpc64le-linux-gnu.tar.gz"
[[xrootdgo]]
arch = "x86_64"
git-tree-sha1 = "7864568fc6d4ba579dc5f6e4c1a729c0c203610e"
os = "macos"

    [[xrootdgo.download]]
    sha256 = "e3fb63c7c8612a5daa6dc2bc592ba0a66c1abe16fbc5c4627984a27780432439"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.32.1+0/xrootdgo.v0.32.1.x86_64-apple-darwin.tar.gz"
[[xrootdgo]]
arch = "x86_64"
git-tree-sha1 = "3a2a6308dbc8957611a663fd94554cf5c672da99"
libc = "glibc"
os = "linux"

    [[xrootdgo.download]]
    sha256 = "05a3289b5c7c90f7d9b08056e34eded1bd357aec02a8ec37c6bc02f0f8a9a8f0"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.32.1+0/xrootdgo.v0.32.1.x86_64-linux-gnu.tar.gz"
[[xrootdgo]]
arch = "x86_64"
git-tree-sha1 = "6a71f73a2d9cc6536f21d5394df96c274cf4e08c"
libc = "musl"
os = "linux"

    [[xrootdgo.download]]
    sha256 = "0cfd0bea41ef64c8967a3f791b84eff6bb6710ee649b150b15011ba98f031d6c"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.32.1+0/xrootdgo.v0.32.1.x86_64-linux-musl.tar.gz"
[[xrootdgo]]
arch = "x86_64"
git-tree-sha1 = "34e3e71cdf5f91d8cdcf6e7787af6aab4026f08e"
os = "freebsd"

    [[xrootdgo.download]]
    sha256 = "a14a3166164582a7b009889cae79c44cdbc8f76d708246641f921ef70c727ba9"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.32.1+0/xrootdgo.v0.32.1.x86_64-unknown-freebsd.tar.gz"
[[xrootdgo]]
arch = "x86_64"
git-tree-sha1 = "afc53eca247ad717309dd9ff9b62d1d9a7f78cb1"
os = "windows"

    [[xrootdgo.download]]
    sha256 = "6130cbc5add48847ce821e27eb84198af8bfcf1b8355e9f1fd52af12c8cd88be"
    url = "https://github.com/JuliaBinaryWrappers/xrootdgo_jll.jl/releases/download/xrootdgo-v0.32.1+0/xrootdgo.v0.32.1.x86_64-w64-mingw32.tar.gz"
